version: '4'
services:
  mysql:
    image: mysql:8.0
    container_name: order-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service #create db on startup
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql #use this file to create a db if not exists in sql cntr in docker